version: "{build}"

image:
  - Visual Studio 2017

build: off

for:
-
  matrix:
    only:
      - image: Visual Studio 2017

  clone_folder: c:\gopath\src\github.com\kumatch\example-go-multios-ci

  environment:
    GOPATH: c:\gopath
    GO111MODULE: on

  test_script:
  - go test -v ./...

  deploy: off

